# Generated by Django 3.2.7 on 2021-10-03 18:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('about', models.CharField(max_length=500, verbose_name='About')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length='1200', verbose_name='Post text')),
                ('post_dt', models.DateField(auto_now=True, verbose_name='Post created time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Author')),
            ],
            options={
                'ordering': ('-post_dt',),
            },
        ),
    ]
